"use strict";
const fs=require("node:fs");
const path=require("node:path");
const {spawnSync}=require("node:child_process");
const test=require("node:test");
const assert=require("node:assert/strict");
const root=path.resolve(__dirname,"..","..");
const file=(p)=>fs.readFileSync(path.join(root,p),"utf8");
const cleanup=file("functions/src/pushAccountCleanup.js");
const bootstrap=file("scripts/bootstrap-production-runtime-build-actas.sh");
const verifier=file("scripts/verify-production-runtime-build-actas.sh");
const changed=()=>`${cleanup}\n${bootstrap}\n${verifier}\n${fs.readFileSync(__filename,"utf8")}`;
const prod="click-save-ai-production";
const runtime="clicksave-auth-cleanup@click-save-ai-production.iam.gserviceaccount.com";
const v2="clicksave-v2-runtime@click-save-ai-production.iam.gserviceaccount.com";
const esc=(s)=>s.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
const has=(s,r)=>assert.match(s,r);
const no=(s,r)=>assert.doesNotMatch(s,r);

test("1 dedicated v1 runtime SA derived correctly",()=>{has(cleanup,/firebase-functions\/v1/);has(cleanup,/runWith\s*\(\s*\{\s*serviceAccount:\s*authCleanupServiceAccount/);has(verifier,new RegExp(esc(runtime)));});
test("2 default appspot SA no longer required",()=>no(changed(),/appspot\.gserviceaccount\.com/));
test("3 Production SA exact identity",()=>{has(cleanup,new RegExp(esc(runtime)));has(cleanup,new RegExp(`equals\\(["']${esc(prod)}["']\\)`));});
test("4 staging cannot reference Production SA",()=>{has(cleanup,/thenElse\(PRODUCTION_AUTH_CLEANUP_SERVICE_ACCOUNT,\s*["']default["']\)/);const p=path.join(root,".github/workflows/deploy-staging.yml");if(fs.existsSync(p))no(fs.readFileSync(p,"utf8"),new RegExp(esc(runtime)));});
test("5 legacy cannot reference Production SA",()=>{has(verifier,/clickandsaveai\|clickandsaveai-staging/);has(verifier,/staging\/legacy deploy principal reference present/);});
test("6 missing dedicated v1 runtime SA can be created only by exact Production bootstrap",()=>{has(bootstrap,/service-accounts create "\$EXPECTED_RUNTIME_SA_ID"/);assert.ok(bootstrap.indexOf('PROJECT_ID must be exactly')<bootstrap.indexOf('service-accounts create'));});
test("7 existing dedicated SA is reused idempotently",()=>{has(bootstrap,/describe_exact_service_account_email\(\) \{[\s\S]*?gcloud iam service-accounts describe "\$email"/);has(bootstrap,/runtime_email="\$\(describe_exact_service_account_email "\$EXPECTED_RUNTIME_SA"\)"/);has(bootstrap,/if \[\[ -z "\$runtime_email" \]\]; then/);});
test("8 zero user-managed keys",()=>{has(bootstrap,/--managed-by=user/);has(verifier,/--managed-by=user/);});
test("9 roles datastore user exact runtime project privilege",()=>{has(bootstrap,/EXPECTED_RUNTIME_ROLE="roles\/datastore\.user"/);has(verifier,/V1_RUNTIME_ROLE="roles\/datastore\.user"/);});
test("10 broad runtime roles rejected",()=>{has(bootstrap,/unexpected project role/);has(verifier,/dedicated v1 runtime SA holds unexpected project role/);has(verifier,/roles\/owner/);});
test("11 deploy SA actAs only on individual runtime SA",()=>{has(bootstrap,/iam service-accounts add-iam-policy-binding "\$sa"/);has(bootstrap,/roles\/iam\.serviceAccountUser/);});
test("12 no project-wide Service Account User",()=>{no(bootstrap,/projects add-iam-policy-binding[^\n]*roles\/iam\.serviceAccountUser/);has(verifier,/project-wide roles\/iam\.serviceAccountUser exists/);});
test("13 dedicated v2 runtime remains independently proven",()=>{has(verifier,new RegExp(esc(v2)));has(verifier,/v2 runtime not independently proven/);});
test("14 Cloud Build remains live-discovered",()=>has(verifier,/gcloud builds get-default-service-account --project="\$P" --region="\$REGION" --format='value\(serviceAccountEmail\)'/));
test("15 overlapping build runtime identities deduplicated",()=>{has(verifier,/add_unique "\$BUILD_SA" INTENDED/);has(bootstrap,/append_unique "\$BUILD_SA" INTENDED_SAS/);});
test("16 no App Engine creation command anywhere",()=>no(changed(),/gcloud\s+app\s+create/));
test("17 no API enablement",()=>no(changed(),/gcloud\s+services\s+enable/));
test("18 no deployment",()=>{no(changed(),/firebase\s+deploy/);no(changed(),/gcloud\s+functions\s+deploy/);});
test("19 exact Production target lock",()=>{has(bootstrap,/PROJECT_ID must be exactly \$EXPECTED_PROJECT_ID/);has(verifier,/PROJECT_ID must be exactly \$P/);has(verifier,/N=991489557172/);has(verifier,/RID=1314210715/);});
test("20 bash syntax",()=>{for(const p of ["scripts/bootstrap-production-runtime-build-actas.sh","scripts/verify-production-runtime-build-actas.sh"]){const r=spawnSync("bash",["-n",path.join(root,p)],{encoding:"utf8"});assert.equal(r.status,0,r.stderr);}});
test("21 changed-file secret scan",()=>{const s=changed();no(s,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/);no(s,/AIza[0-9A-Za-z_-]{30,}/);no(s,/gh[pousr]_[A-Za-z0-9]{20,}/);});
test("22 service-account-key creation scan",()=>no(changed(),/service-accounts\s+keys\s+create/));
